dtmc

module Prova

home : bool init false;
videoe : bool init false;
news : bool init false;
social : bool init false;
start : bool init true;
calendar : bool init false;
map : bool init false;
athletics : bool init false;
goal : bool init false;
eclass : bool init false;
people : bool init false;

[] ( (eclass=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) ) -> 1.0 : (map'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (people'=false);
[] ( (goal=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (athletics=false) & (map=false) & (people=false) ) -> 1.0 : (goal'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (calendar=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) ) -> 0.33333334 : (athletics'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (map'=false) & (people'=false) + 0.6666667 : (goal'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (social=true) & (home=false) & (videoe=false) & (news=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) ) -> 0.6 : (social'=true) & (home'=false) & (videoe'=false) & (news'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.2 : (goal'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.2 : (home'=true) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (news=true) & (athletics=true) & (home=false) & (videoe=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (map=false) & (people=false) ) -> 1.0 : (social'=true) & (home'=false) & (videoe'=false) & (news'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (videoe=true) & (home=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) ) -> 0.25 : (calendar'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.5 : (videoe'=true) & (home'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.25 : (goal'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (start=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) ) -> 0.16666667 : (calendar'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.16666667 : (news'=true) & (athletics'=true) & (home'=false) & (videoe'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (map'=false) & (people'=false) + 0.16666667 : (people'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) + 0.33333334 : (videoe'=true) & (home'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.16666667 : (home'=true) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (people=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) ) -> 1.0 : (eclass'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (news=true) & (home=false) & (videoe=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) ) -> 0.6666667 : (news'=true) & (home'=false) & (videoe'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.33333334 : (goal'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (map=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (people=false) ) -> 1.0 : (goal'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (home=true) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) ) -> 0.6666667 : (goal'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (athletics'=false) & (map'=false) & (people'=false) + 0.33333334 : (news'=true) & (home'=false) & (videoe'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false);
[] ( (athletics=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (map=false) & (people=false) ) -> 0.6666667 : (athletics'=true) & (home'=false) & (videoe'=false) & (news'=false) & (social'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (map'=false) & (people'=false) + 0.33333334 : (social'=true) & (home'=false) & (videoe'=false) & (news'=false) & (start'=false) & (calendar'=false) & (eclass'=false) & (goal'=false) & (athletics'=false) & (map'=false) & (people'=false);

endmodule

rewards "labels"

(eclass=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) : 71.42857;
(goal=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (athletics=false) & (map=false) & (people=false) : 0.0;
(calendar=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) : 77.77778;
(social=true) & (home=false) & (videoe=false) & (news=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) : 71.42857;
(news=true) & (athletics=true) & (home=false) & (videoe=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (map=false) & (people=false) : 86.666664;
(videoe=true) & (home=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) : 85.71429;
(start=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) : 83.33333;
(people=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) : 85.71429;
(news=true) & (home=false) & (videoe=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) : 80.0;
(map=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (people=false) : 60.000004;
(home=true) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (athletics=false) & (map=false) & (people=false) : 80.0;
(athletics=true) & (home=false) & (videoe=false) & (news=false) & (social=false) & (start=false) & (calendar=false) & (eclass=false) & (goal=false) & (map=false) & (people=false) : 80.0;

endrewards
